// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelacaoTcc.Infrastructure;

namespace RelacaoTcc.Migrations
{
    [DbContext(typeof(AppContexto))]
    partial class AppContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RelacaoTcc.Dominio.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular");

                    b.Property<bool>("IsAtivo");

                    b.Property<string>("Nome");

                    b.Property<string>("Profissao");

                    b.Property<string>("RA");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("RelacaoTcc.Dominio.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAtivo");

                    b.Property<string>("Nome");

                    b.Property<string>("Registro");

                    b.HasKey("Id");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("RelacaoTcc.Dominio.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataFim");

                    b.Property<DateTime>("DataIni");

                    b.Property<string>("Descricao");

                    b.Property<bool>("IsAtivo");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("RelacaoTcc.Dominio.Models.ProjetoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlunoId");

                    b.Property<bool>("IsAtivo");

                    b.Property<int>("ProjetoId");

                    b.HasKey("Id");

                    b.ToTable("ProjetosAlunos");
                });

            modelBuilder.Entity("RelacaoTcc.Dominio.Models.ProjetoProfessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAtivo");

                    b.Property<int>("ProfessorId");

                    b.Property<int>("ProjetoId");

                    b.HasKey("Id");

                    b.ToTable("ProjetosProfessores");
                });
#pragma warning restore 612, 618
        }
    }
}
